version: '2'
services:
  nginx:
    build: ./nginx/
    container_name: nginx
    volumes:
      - ./nginx/www/:/var/www/nginx
    ports:
      - 80:80
    networks:
      - se_backend
  hbase:
    build: ./hbase/
    container_name: hbase
    ports:
      - 2181:2181
      - 8085:8085
      - 9095:9095
      - 16010:16010
      - 16301:16301
    networks:
      se_backend:
        aliases:
          - zookeeper
  grproxy:
    build: ./grproxy/
    container_name: grproxy
    networks:
      - se_frontend
      - se_backend
  #gserve1:
  #gserve2:

networks:
  se_frontend:
    driver: bridge
  se_backend:
    driver: bridge
